### ISSUE TITLE
引用请备注

### ISSUE THREAD

**Issue by seisgo** [xiamenwcy/EllipseFitting#1]
虽然说github代码是开源的，但是您明显在别人代码上进行修改然后发布，作为开源享用的基本素质也应该标明自己引用或参考了别人的工作吧。
况且您仅仅是将矩阵表示由指针形式改为用eigen库来实现，其他函数包括备注基本都是从我开源的代码照搬或简单修改。

引用请参考：https://github.com/seisgo/EllipseFit

**Comment by xiamenwcy** [comment]
sorry啊，我会标一下

**Comment by seisgo** [comment]
谢谢！
